/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Modelo.Cena;
import Modelo.MatrizTransf;
import Modelo.Poliedro;
import static Modelo.Ponto.Coordenada.*;
import static Modelo.MatrizTransf.*;
import static Modelo.MatrizTransf.TipoTransf.*;
import static Modelo.Poliedro.TipoModif.*;
import java.awt.FileDialog;
import java.awt.Frame;
import java.io.BufferedReader;
import java.io.StringReader;
import java.util.ArrayDeque;
import java.util.Queue;
import javax.swing.JOptionPane;

/**
 *
 * @author Murillo Machado
 */
public class PainelPrincipal extends javax.swing.JFrame {
    
    private Cena c;
    private String saveFilename;
    private ArrayDeque<String> undo;
    private final static int LIMITE_UNDO = 20;

    /**
     * Creates new form painelPrincipal
     */
    public PainelPrincipal() {
        this.c = new Cena();
        this.saveFilename = "";
        this.undo = new ArrayDeque<>();
        zerarUndo();
        
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        criarPoliedro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        spNumLados = new javax.swing.JSpinner();
        spAltura = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        spTamLado = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botAdicionarPoliedro = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spTranslX = new javax.swing.JSpinner();
        spTranslY = new javax.swing.JSpinner();
        spTranslZ = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spEscalaX = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        spEscalaY = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        spEscalaZ = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        botaoBevel = new javax.swing.JButton();
        botaoTwist = new javax.swing.JButton();
        botaoBend = new javax.swing.JButton();
        cbSelecionar = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        spRotX = new javax.swing.JSpinner();
        spRotY = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        spRotZ = new javax.swing.JSpinner();
        botaoTransformar = new javax.swing.JButton();
        botaoResetarValores = new javax.swing.JButton();
        painelXY = new PainelVisualizacao(c, X, Y);
        jLabel1 = new javax.swing.JLabel();
        painelZX = new PainelVisualizacao(c, Z, X);
        jLabel2 = new javax.swing.JLabel();
        painelZY = new PainelVisualizacao(c, Z, Y);
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNovo = new javax.swing.JMenuItem();
        menuAbrir = new javax.swing.JMenuItem();
        menuSalvar = new javax.swing.JMenuItem();
        menuSalvarComo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuDesfazer = new javax.swing.JMenuItem();
        menuExcluir = new javax.swing.JMenuItem();

        jLabel3.setText("Numero de lados: ");

        spNumLados.setModel(new javax.swing.SpinnerNumberModel(3, 3, 20, 1));

        spAltura.setModel(new javax.swing.SpinnerNumberModel(50.0d, null, null, 1.0d));

        jLabel18.setText("Altura: ");

        spTamLado.setModel(new javax.swing.SpinnerNumberModel(50.0d, 1.0d, null, 1.0d));

        jLabel19.setText("Tamanho lado:");

        javax.swing.GroupLayout criarPoliedroLayout = new javax.swing.GroupLayout(criarPoliedro);
        criarPoliedro.setLayout(criarPoliedroLayout);
        criarPoliedroLayout.setHorizontalGroup(
            criarPoliedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criarPoliedroLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(criarPoliedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(criarPoliedroLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(spTamLado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(criarPoliedroLayout.createSequentialGroup()
                        .addGroup(criarPoliedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(criarPoliedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spNumLados)
                            .addComponent(spAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66))
        );
        criarPoliedroLayout.setVerticalGroup(
            criarPoliedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criarPoliedroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(criarPoliedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spNumLados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(criarPoliedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(spAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(criarPoliedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(spTamLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 300));

        botAdicionarPoliedro.setText("Adicionar Poliedro");
        botAdicionarPoliedro.setToolTipText("Adiciona um novo poliedro a cena");
        botAdicionarPoliedro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdicionarPoliedroActionPerformed(evt);
            }
        });

        jLabel4.setText("Transformações");

        jLabel8.setText("Rotação:");

        jLabel9.setText("Translação:");

        spTranslX.setModel(new javax.swing.SpinnerNumberModel());

        spTranslY.setModel(new javax.swing.SpinnerNumberModel());

        spTranslZ.setModel(new javax.swing.SpinnerNumberModel());

        jLabel10.setText("X");

        jLabel11.setText("Y");

        jLabel12.setText("Z");

        jLabel13.setText("Escala:");

        spEscalaX.setModel(new javax.swing.SpinnerNumberModel(1.0f, null, null, 1.0f));

        jLabel14.setText("X");

        spEscalaY.setModel(new javax.swing.SpinnerNumberModel(1.0f, null, null, 1.0f));

        jLabel15.setText("Y");

        spEscalaZ.setModel(new javax.swing.SpinnerNumberModel(1.0f, null, null, 1.0f));

        jLabel16.setText("Z");

        jLabel17.setText("Modificadores");

        botaoBevel.setText("Bevel");
        botaoBevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBevelActionPerformed(evt);
            }
        });

        botaoTwist.setText("Twist");
        botaoTwist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTwistActionPerformed(evt);
            }
        });

        botaoBend.setText("Bend");
        botaoBend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBendActionPerformed(evt);
            }
        });

        cbSelecionar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar poliedro..." }));
        cbSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelecionarActionPerformed(evt);
            }
        });

        jLabel21.setText("X");

        spRotX.setModel(new javax.swing.SpinnerNumberModel());

        spRotY.setModel(new javax.swing.SpinnerNumberModel());

        jLabel22.setText("Y");

        jLabel23.setText("Z");

        spRotZ.setModel(new javax.swing.SpinnerNumberModel());

        botaoTransformar.setText("Aplicar transformação");
        botaoTransformar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTransformarActionPerformed(evt);
            }
        });

        botaoResetarValores.setText("Resetar valores");
        botaoResetarValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoResetarValoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(botaoTransformar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbSelecionar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spRotY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spRotZ, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14))))
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(spTranslY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spTranslZ, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spEscalaZ, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(14, 14, 14))))))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botAdicionarPoliedro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 7, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(75, 75, 75)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(spEscalaY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(16, 16, 16)
                                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(23, 23, 23)
                                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(spRotX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(16, 16, 16)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(spEscalaX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(spTranslX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 91, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoResetarValores))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoTwist)
                            .addComponent(botaoBevel)
                            .addComponent(botaoBend))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(botAdicionarPoliedro)
                .addGap(8, 8, 8)
                .addComponent(cbSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(botaoResetarValores))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spRotX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spTranslX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spTranslY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spTranslZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spRotY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spRotZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spEscalaX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spEscalaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spEscalaZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(botaoTransformar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(botaoBevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoTwist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoBend)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelXY.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelXY.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel1.setText("Visualização XY");

        javax.swing.GroupLayout painelXYLayout = new javax.swing.GroupLayout(painelXY);
        painelXY.setLayout(painelXYLayout);
        painelXYLayout.setHorizontalGroup(
            painelXYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelXYLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 224, Short.MAX_VALUE))
        );
        painelXYLayout.setVerticalGroup(
            painelXYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelXYLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 282, Short.MAX_VALUE))
        );

        painelZX.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelZX.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel2.setText("Visualização ZX");

        javax.swing.GroupLayout painelZXLayout = new javax.swing.GroupLayout(painelZX);
        painelZX.setLayout(painelZXLayout);
        painelZXLayout.setHorizontalGroup(
            painelZXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelZXLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 224, Short.MAX_VALUE))
        );
        painelZXLayout.setVerticalGroup(
            painelZXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelZXLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 282, Short.MAX_VALUE))
        );

        painelZY.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelZY.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel20.setText("Visualização ZY");

        javax.swing.GroupLayout painelZYLayout = new javax.swing.GroupLayout(painelZY);
        painelZY.setLayout(painelZYLayout);
        painelZYLayout.setHorizontalGroup(
            painelZYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelZYLayout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 224, Short.MAX_VALUE))
        );
        painelZYLayout.setVerticalGroup(
            painelZYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelZYLayout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 282, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivo");

        menuNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNovo.setText("Novo");
        menuNovo.setToolTipText("Cria uma nova cena");
        menuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoActionPerformed(evt);
            }
        });
        jMenu1.add(menuNovo);

        menuAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuAbrir.setText("Abrir");
        menuAbrir.setToolTipText("Abre uma cena salva do arquivo");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(menuAbrir);

        menuSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSalvar.setText("Salvar");
        menuSalvar.setToolTipText("Salva a cena atual");
        menuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalvarActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalvar);

        menuSalvarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuSalvarComo.setText("Salvar como...");
        menuSalvarComo.setToolTipText("Salva a cena atual");
        menuSalvarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalvarComoActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalvarComo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        menuDesfazer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        menuDesfazer.setText("Desfazer");
        menuDesfazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDesfazerActionPerformed(evt);
            }
        });
        jMenu2.add(menuDesfazer);

        menuExcluir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        menuExcluir.setText("Excluir");
        menuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirActionPerformed(evt);
            }
        });
        jMenu2.add(menuExcluir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelZY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelXY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelZX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelXY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelZX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(painelZY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private double toRad(double x) {
        return x * Math.PI / 180;
    }
    
    private void repaintAll() {
        painelXY.repaint();
        painelZX.repaint();
        painelZY.repaint();
    }
    
    private void resetarCBSelecionar() {
        cbSelecionar.removeAllItems();
        cbSelecionar.addItem("Selecionar poliedro...");
        for(int i = 0; i < c.poliedros.size(); i++) {
            cbSelecionar.addItem("" + (i+1));
        }
        cbSelecionar.setSelectedIndex(0);
        cbSelecionarActionPerformed(null);
    }
    
    private void setCena(Cena c) {
        
        this.c = c;
        resetarCBSelecionar();
        
        ((PainelVisualizacao) painelXY).setCena(c);
        ((PainelVisualizacao) painelZX).setCena(c);
        ((PainelVisualizacao) painelZY).setCena(c);
        
        repaintAll();
    }
    
    private void adicionarUndo() {
        if(undo.size() >= LIMITE_UNDO) {
            undo.removeFirst();
        }
        undo.addLast(c.stringSalvar());
    }
    
    private void zerarUndo() {
        undo.clear();
        undo.addLast(c.stringSalvar());
    }
    
    private void actionModificar(Poliedro.TipoModif modif) {
        
        Poliedro p = c.getSelecionado();
        if(p == null) {
            JOptionPane.showMessageDialog(null, "Selecione um poliedro!");
            return;
        }
        
        while (true) {
            String val = JOptionPane.showInputDialog("Valor: ");
            
            if (val == null) {
                return;
            }
            
            try {
                val = val.replace(',', '.');
                double v = Double.parseDouble(val);
                
                if(modif == TWIST || modif == BEND) {
                    v = toRad(v);
                }
                
                p.modificar(modif, v);
                break;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Valor inválido");
            }
        }

        repaintAll();
        adicionarUndo();
    }
    
    private void menuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoActionPerformed
        setCena(new Cena());
        saveFilename = "";
        zerarUndo();
    }//GEN-LAST:event_menuNovoActionPerformed

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        FileDialog fd = new FileDialog(new Frame(), "Abrir arquivo", FileDialog.LOAD);
        fd.setFile("*.john");
        fd.setVisible(true);
        
        if(fd.getFile() != null) {
            String filename = fd.getDirectory() + fd.getFile();
            saveFilename = filename;
            setCena(new Cena(Cena.ler(filename)));
            zerarUndo();
        }
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalvarActionPerformed
        if("".equals(saveFilename)) {
            menuSalvarComoActionPerformed(null);
        } else {
            c.salvar(saveFilename);
        }
    }//GEN-LAST:event_menuSalvarActionPerformed

    private void menuSalvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalvarComoActionPerformed
        FileDialog fd = new FileDialog(new Frame(), "Salvar arquivo", FileDialog.SAVE);
        fd.setVisible(true);
        
        if(fd.getFile() != null) {
            String filename = fd.getDirectory() + fd.getFile();
            if(!filename.endsWith(".john")) {
                filename = filename + ".john";
            }
            saveFilename = filename;
            c.salvar(filename);
        }
    }//GEN-LAST:event_menuSalvarComoActionPerformed

    private void menuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirActionPerformed
        c.excluirSelecionado();
        resetarCBSelecionar();
        repaintAll();
        adicionarUndo();
    }//GEN-LAST:event_menuExcluirActionPerformed

    private void cbSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelecionarActionPerformed
        c.selecionado = cbSelecionar.getSelectedIndex() - 1;
        repaintAll();
    }//GEN-LAST:event_cbSelecionarActionPerformed

    private void botaoBendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBendActionPerformed
        actionModificar(BEND);
    }//GEN-LAST:event_botaoBendActionPerformed

    private void botaoTwistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTwistActionPerformed
        actionModificar(TWIST);
    }//GEN-LAST:event_botaoTwistActionPerformed

    private void botaoBevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBevelActionPerformed
        actionModificar(BEVEL);
    }//GEN-LAST:event_botaoBevelActionPerformed

    private void botAdicionarPoliedroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdicionarPoliedroActionPerformed

        int opcao = JOptionPane.showOptionDialog(null, criarPoliedro, "Criar Poliedro", JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE, null, new String[]{"OK", "Cancelar"}, null);

        if(opcao == 0) {
            int numLados = (Integer) spNumLados.getValue();
            double altura = (Double) spAltura.getValue();
            double tamLado = (Double) spTamLado.getValue();

            c.poliedros.add(new Poliedro(numLados, tamLado, altura));
            cbSelecionar.addItem("" + c.poliedros.size());
            cbSelecionar.setSelectedIndex(c.poliedros.size());
            cbSelecionarActionPerformed(null);

            repaintAll();
            adicionarUndo();
        }
    }//GEN-LAST:event_botAdicionarPoliedroActionPerformed

    private void botaoTransformarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTransformarActionPerformed

        Poliedro p = c.getSelecionado();
        if(p == null) {
            JOptionPane.showMessageDialog(null, "Selecione um poliedro!");
            return;
        }
        
        double rotX = ((Integer) spRotX.getValue()).floatValue();
        double rotY = ((Integer) spRotY.getValue()).floatValue();
        double rotZ = ((Integer) spRotZ.getValue()).floatValue();
        
        double translX = ((Integer) spTranslX.getValue()).floatValue();
        double translY = ((Integer) spTranslY.getValue()).floatValue();
        double translZ = ((Integer) spTranslZ.getValue()).floatValue();
        
        double escalaX = ((Float) spEscalaX.getValue());
        double escalaY = ((Float) spEscalaY.getValue());
        double escalaZ = ((Float) spEscalaZ.getValue());
        
        p.transladar(translX, translY, translZ);
        
        p.mult(new MatrizTransf(ROTACAO, toRad(rotZ), TipoRot.Z).mult(
               new MatrizTransf(ROTACAO, toRad(rotY), TipoRot.Y).mult(
               new MatrizTransf(ROTACAO, toRad(rotX), TipoRot.X).mult(
               new MatrizTransf(ESCALA, escalaX, escalaY, escalaZ)))));
        
        repaintAll();
        adicionarUndo();
    }//GEN-LAST:event_botaoTransformarActionPerformed

    private void botaoResetarValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoResetarValoresActionPerformed
        spRotX.setValue(0);
        spRotY.setValue(0);
        spRotZ.setValue(0);
        spTranslX.setValue(0);
        spTranslY.setValue(0);
        spTranslZ.setValue(0);
        spEscalaX.setValue((float) 1.0);
        spEscalaY.setValue((float) 1.0);
        spEscalaZ.setValue((float) 1.0);
    }//GEN-LAST:event_botaoResetarValoresActionPerformed

    private void menuDesfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDesfazerActionPerformed
        if(undo.size() > 1) {
            undo.removeLast();
            BufferedReader br = new BufferedReader(new StringReader(undo.getLast()));
            setCena(new Cena(br));
        }
    }//GEN-LAST:event_menuDesfazerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAdicionarPoliedro;
    private javax.swing.JButton botaoBend;
    private javax.swing.JButton botaoBevel;
    private javax.swing.JButton botaoResetarValores;
    private javax.swing.JButton botaoTransformar;
    private javax.swing.JButton botaoTwist;
    private javax.swing.JComboBox<String> cbSelecionar;
    private javax.swing.JPanel criarPoliedro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenuItem menuDesfazer;
    private javax.swing.JMenuItem menuExcluir;
    private javax.swing.JMenuItem menuNovo;
    private javax.swing.JMenuItem menuSalvar;
    private javax.swing.JMenuItem menuSalvarComo;
    private javax.swing.JPanel painelXY;
    private javax.swing.JPanel painelZX;
    private javax.swing.JPanel painelZY;
    private javax.swing.JSpinner spAltura;
    private javax.swing.JSpinner spEscalaX;
    private javax.swing.JSpinner spEscalaY;
    private javax.swing.JSpinner spEscalaZ;
    private javax.swing.JSpinner spNumLados;
    private javax.swing.JSpinner spRotX;
    private javax.swing.JSpinner spRotY;
    private javax.swing.JSpinner spRotZ;
    private javax.swing.JSpinner spTamLado;
    private javax.swing.JSpinner spTranslX;
    private javax.swing.JSpinner spTranslY;
    private javax.swing.JSpinner spTranslZ;
    // End of variables declaration//GEN-END:variables

}
